server:
  port: 8807
spring:
  application:
    name: CONSUL-CLIENT-SIDE
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: foo=bar, baz
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    org.springframework: info