server:
  port: 9411
spring:
  application:
    name: ZIPKIN-SERVER
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: zipkin-server, support
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}